# Generated by Django 3.2.3 on 2021-10-02 20:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField(max_length=500, null=True)),
                ('payment', models.CharField(choices=[('NOT PAID', 'Not paid'), ('PAID', 'Paid'), ('RECEIVED', 'Received'), ('DISPUTE', 'Dispute')], default='NOT_PAID', max_length=100)),
                ('shipped', models.CharField(choices=[('ORDERED', 'Ordered'), ('PROCESSED', 'Processed'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('RETTURNED', 'Returned'), ('DISPUTE', 'Dispute')], default='ORDERED', max_length=100)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
            ],
        ),
    ]
