# Generated by Django 3.2.10 on 2022-01-24 15:25

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Не оплачено', 'Not_paid'), ('Оплачено', 'Paid'), ('Повернено', 'Received'), ('Оскаржено', 'Dispute')], default='Не оплачено', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.CharField(default=apps.orders.models.get_order_id, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.CharField(choices=[('Замовлено', 'Ordered'), ('Опрацьовано', 'Processed'), ('В доставці', 'Shipped'), ('Отримано', 'Received'), ('Повернено', 'Returned'), ('В розгляді', 'Dispute')], default='Замовлено', max_length=100),
        ),
    ]
