version: '3.7'

services:
  web:
    build: ./shop
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/shop/shop/static
      - media_volume:/home/shop/shop/media
      - service_log:/var/log/shop/shop.log
      - home_volume:/home/shop
    expose:
      - 8000
    environment:
      - ALLOWED_HOSTS=*
      - DEBUG=1
      - DB_NAME=test_shop
      - DB_USER=django
      - DB_PASS=django
      - DB_HOST=postgres
      - DB_PORT=5432
      - SECRET_KEY="SECRET_KEY"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: 'shop_db'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=test_shop
  nginx:
    build: ./nginx
    restart: always
    container_name: shop-nginx
    volumes:
      - static_volume:/home/shop/shop/static
      - media_volume:/home/shop/shop/media
      - access_log:/var/log/nginx/nginx.vhost.access.log;
      - error_log:/var/log/nginx/nginx.vhost.errors.log;
      - certs:/etc/nginx/certs
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
  redis:
    image: redis
    restart: always
    container_name: 'shop_redis'
    command: redis-server
    ports:
      - 6379:6379
  celery:
    build: ./shop
    container_name: 'shop_celery'
    command: celery -A shop worker -B
    volumes:
      - home_volume:/home/shop
    links:
      - redis
    depends_on:
      - web
      - redis
volumes:
  service_log:
  postgres_data:
  static_volume:
  media_volume:
  access_log:
  error_log:
  home_volume:
  certs:
