version: '3.7'

services:
  web:
    build: ./shop
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/shop/shop/static
      - media_volume:/home/shop/shop/media
      - service_log:/var/log/shop/shop.log
      - home_volume:/home/shop
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: 'shop_db'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    restart: always
    container_name: shop-nginx
    volumes:
      - static_volume:/home/shop/shop/static
      - media_volume:/home/shop/shop/media
      - public:/var/www/html
      - conf.d:/etc/nginx/conf.d
      - conf:/etc/nginx/ssl
      - data:/var/www/certbot
      - access_log:/var/log/nginx/nginx.vhost.access.log;
      - error_log:/var/log/nginx/nginx.vhost.errors.log;
      - certs:/etc/nginx/certs
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
      - certbot
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email
      yariquezz@gmail.com --agree-tos --no-eff-email -d yarique.com -d
      www.yarique.com
    volumes:
      - conf:/etc/letsencrypt
      - logs:/var/log/letsencrypt
      - data:/var/www/certbot
  redis:
    image: redis
    restart: always
    container_name: 'shop_redis'
    command: redis-server
    ports:
      - 6379:6379
  celery:
    build: ./shop
    container_name: 'shop_celery'
    command: celery -A shop worker -B
    volumes:
      - home_volume:/home/shop
    links:
      - redis
    depends_on:
      - web
      - redis

volumes:
  service_log: null
  postgres_data: null
  static_volume: null
  media_volume: null
  access_log: null
  error_log: null
  home_volume: null
  certs: null
  conf: null
  public: null
  conf.d: null
  data: null
  logs: null
