version: '3.7'

services:
  web:
    build: ./shop
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/shop/shop/static
      - media_volume:/home/shop/shop/media
      - service_log:/var/log/shop/shop.log
      - home_volume:/home/shop
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: 'shop_db'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    restart: always
    container_name: shop-nginx
    volumes:
      - static_volume:/home/shop/shop/static
      - media_volume:/home/shop/shop/media
      - access_log:/var/log/nginx/nginx.vhost.access.log;
      - error_log:/var/log/nginx/nginx.vhost.errors.log;
      - certs:/etc/nginx/certs
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
  keycloak:
    image: jboss/keycloak:latest
    env_file:
      - ./.env
    ports:
      - 8080:8080
    depends_on:
      - postgres
  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: [ "--reporter.grpc.host-port=192.168.0.110:14250" ]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
  redis:
    image: redis
    restart: always
    container_name: 'shop_redis'
    command: redis-server
    ports:
      - 6379:6379
  celery:
    build: ./shop
    container_name: 'shop_celery'
    command: celery -A shop worker -B
    volumes:
      - home_volume:/home/shop
    links:
      - redis
    depends_on:
      - web
      - redis

volumes:
  service_log: null
  postgres_data: null
  static_volume: null
  media_volume: null
  access_log: null
  error_log: null
  home_volume: null
  certs: null
