# Generated by Django 3.2.3 on 2021-12-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcard',
            name='benefits',
            field=models.JSONField(null=True),
        ),
    ]
