name: Django predeployment CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - name: Start actions
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r shop/requirements.txt
      - name: Code Quality
        run: |
          pip install flake8
          flake8 --ignore=E501,F401 .
      - name: Run Tests
        run: |
          coverage run shop/manage.py test apps
